name: "validate conventional commits"

on:
  workflow_call:

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate commits
        run: |
          set -euo pipefail
          commit_range="origin/${GITHUB_BASE_REF}.."
          # Check for conventional commits in the specified range
          commits=$(git log --pretty=format:"%s" --no-merges $commit_range | grep -E '^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert)(\(.+\))?!?: .+' || true)
          if [ -z "$commits" ]; then
            echo "No conventional commits found. Please include at least one conventional commit."
            exit 1
          fi

          # Get the last commit message
          last_commit=$(git log --pretty=format:"%s" --no-merges $commit_range | head -n 1 || true)
          # Extract the type if it's a conventional commit
          last_commit_type=$(echo "$last_commit" | grep -Eo '^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert)' || true)
          if [ -z "$last_commit_type" ]; then
            echo "No conventional commit found on the last commit, no build will be triggered."
            echo "build=false" >> "$GITHUB_OUTPUT"
          else
            echo "Conventional commit found on the last commit, evalutaing whether to trigger a build."
            # If feat or fix, trigger a build
            if [ "$last_commit_type" == "chore" ] || [ "$last_commit_type" == "style" ] || [ "$last_commit_type" == "docs" ]; then
              echo "Conventional commit type is chore, style or docs. No build will be triggered."
              echo "build=false" >> "$GITHUB_OUTPUT"
            else
              echo "Conventional commit type found to trigger a build."
              echo "build=true" >> "$GITHUB_OUTPUT"
            fi
          fi
        shell: bash
