name: "validate conventional commits"

on:
  workflow_call:

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate commits
        run: |
          # Get the commit range for the current branch
          commit_range="origin/${GITHUB_BASE_REF}.."
          echo "Commit range: $commit_range"
          # Check for conventional commits in the specified range
          commits=$(git log --pretty=format:"%s" $commit_range | grep -E '^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert)(\(.+\))?!?: .+' || true)
          echo "Commits: $commits"
          if [ -z "$commits" ]; then
            echo "No conventional commits found. Please include at least one conventional commit."
            exit 1
          fi
          last_commit=$(git log --pretty=format:"%s" -1)
          echo "Last commit: $last_commit"
        shell: bash
