name: PR Title Check

on:
  pull_request:
   types: [opened, synchronize]

jobs:
  print_title_of_pr:
    runs-on: ubuntu-20.04
    steps:
    # - name: Print Title of PR
    #   id: print_title
    #   run: echo "title=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT

    # - name: Output Title of PR
    #   run:
    #     echo "The title of the PR is $title"
      - name: Set color
        id: color-selector
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"