name: PR Title Check

on:
  pull_request:
   types: [opened, synchronize, edited]

jobs:
  print_title_of_pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Print name of PR
        id: print-pr-title
        run: echo "SELECTED_PR_TITLE=${{ github.event.pull_request.title }}" >> "$GITHUB_OUTPUT"
      - name: Verify name of PR
        env:
          SELECTED_PR_TITLE: ${{ steps.print-pr-title.outputs.SELECTED_PR_TITLE }}
        run: |
          if [[ §SELECTED_PR_TITLE = "test" ]]; then
            echo "The PR title is correct"
          else
            echo "The PR title is incorrect"
            exit 1
          fi
