name: PR Title Check

on:
  pull_request:
   types: [opened, synchronize, edited]

jobs:
  print_title_of_pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Get the name of the PR
        id: pr-title
        run: echo "PR_TITLE=${{ github.event.pull_request.title }}" >> "$GITHUB_OUTPUT"
      - name: Verify name of PR
        env:
          PR_TITLE: ${{ steps.pr-title.outputs.PR_TITLE }}
        run: |
          if [[ "${PR_TITLE}" == feat:* ]]; then
            echo "The PR title is correct"
          else
            echo "The PR title is incorrect. The name of the PR is $PR_TITLE"
            exit 1
          fi
