name: PR Title Check

on:
  pull_request:
   types: [opened, synchronize, edited]

jobs:
  validate_pr_title:
    runs-on: ubuntu-20.04
    env:
      VALID_COMMITS: '("feat:" "fix:" "docs:" "chore:" "test:")' # Array format
    steps:
      - name: Get the name of the PR
        id: pr-title
        run: echo "PR_TITLE=${{ github.event.pull_request.title }}" >> "$GITHUB_OUTPUT"
      - name: Verify name of PR
        env:
          PR_TITLE: ${{ steps.pr-title.outputs.PR_TITLE }}
          VALID_COMMITS: ${{ env.VALID_COMMITS }}
        run: |
          # Use VALID_COMMITS as a Bash array
          VALID_ARRAY=${VALID_COMMITS[@]}

          # Initialize a flag to indicate if the title is valid
          IS_VALID=false

          # Check if PR_TITLE starts with any of the valid prefixes
          for VALID_PREFIX in "${VALID_ARRAY[@]}"; do
            if [[ "${PR_TITLE}" == "${VALID_PREFIX}"* ]]; then
              IS_VALID=true
              break
            fi
          done

          # Decide based on the validity flag
          if [[ "${IS_VALID}" == "true" ]]; then
            echo "The PR title is valid: ${PR_TITLE}"
          else
            echo "The PR title is invalid. It must start with one of: ${VALID_ARRAY[*]}"
            exit 1
          fi